package migrations

const propositionBindingMigration = "000050_evidence_ingestion_proposition_bindings.up.sql"

var propositionBindingFunctions = []requiredFixedCoreFunction{
	{Migration: propositionBindingMigration, Name: "proposition_digest", Arguments: "text[]", Result: "text", RequirePublicExecuteRevoked: true},
	{Migration: propositionBindingMigration, Name: "proposition_check_member", Result: "trigger", SecurityDefiner: true, Config: []string{"search_path=pg_catalog", "row_security=off"}, RequirePublicExecuteRevoked: true},
	{Migration: propositionBindingMigration, Name: "proposition_check_complete", Result: "trigger", SecurityDefiner: true, Config: []string{"search_path=pg_catalog", "row_security=off"}, RequirePublicExecuteRevoked: true},
	{Migration: propositionBindingMigration, Name: "proposition_immutable", Result: "trigger", SecurityDefiner: true, Config: []string{"search_path=pg_catalog", "row_security=off"}, RequirePublicExecuteRevoked: true},
	{Migration: propositionBindingMigration, Name: "proposition_binding_transition_guard", Result: "trigger", SecurityDefiner: true, Config: []string{"search_path=pg_catalog", "row_security=off"}, RequirePublicExecuteRevoked: true},
}
var propositionBindingTriggers = []requiredFixedCoreTrigger{
	{Migration: propositionBindingMigration, Name: "proposition_immutable_rows", Table: "canonical_propositions", Function: "proposition_immutable", TriggerType: 1 | 2 | 8 | 16},
	{Migration: propositionBindingMigration, Name: "proposition_immutable_table", Table: "canonical_propositions", Function: "proposition_immutable", TriggerType: 2 | 32},
	{Migration: propositionBindingMigration, Name: "proposition_binding_immutable_rows", Table: "canonical_proposition_bindings", Function: "proposition_immutable", TriggerType: 1 | 2 | 8 | 16},
	{Migration: propositionBindingMigration, Name: "proposition_binding_immutable_table", Table: "canonical_proposition_bindings", Function: "proposition_immutable", TriggerType: 2 | 32},
	{Migration: propositionBindingMigration, Name: "proposition_binding_immutable_rows", Table: "canonical_proposition_binding_events", Function: "proposition_immutable", TriggerType: 1 | 2 | 8 | 16},
	{Migration: propositionBindingMigration, Name: "proposition_binding_immutable_table", Table: "canonical_proposition_binding_events", Function: "proposition_immutable", TriggerType: 2 | 32},
	{Migration: propositionBindingMigration, Name: "proposition_member_guard", Table: "canonical_proposition_bindings", Function: "proposition_check_member", TriggerType: 1 | 2 | 4},
	{Migration: propositionBindingMigration, Name: "proposition_binding_transition", Table: "canonical_proposition_binding_events", Function: "proposition_binding_transition_guard", TriggerType: 1 | 2 | 4},
	{Migration: propositionBindingMigration, Name: "proposition_complete", Table: "canonical_propositions", Function: "proposition_check_complete", TriggerType: 1 | 4, Constraint: true, Deferrable: true, InitiallyDeferred: true},
}
var propositionBindingColumns = []requiredFixedCoreColumn{
	{Migration: propositionBindingMigration, Table: "canonical_propositions", Name: "proposition_id", DataType: "text", NotNull: true},
	{Migration: propositionBindingMigration, Table: "canonical_propositions", Name: "namespace_id", DataType: "text", NotNull: true},
	{Migration: propositionBindingMigration, Table: "canonical_propositions", Name: "local_id", DataType: "text", NotNull: true},
	{Migration: propositionBindingMigration, Table: "canonical_propositions", Name: "scope_ref", DataType: "text", NotNull: true},
	{Migration: propositionBindingMigration, Table: "canonical_propositions", Name: "revision", DataType: "text", NotNull: true},
	{Migration: propositionBindingMigration, Table: "canonical_propositions", Name: "definition", DataType: "text", NotNull: true},
	{Migration: propositionBindingMigration, Table: "canonical_proposition_bindings", Name: "request_id", DataType: "text", NotNull: true},
	{Migration: propositionBindingMigration, Table: "canonical_proposition_bindings", Name: "proposition_id", DataType: "text", NotNull: true},
	{Migration: propositionBindingMigration, Table: "canonical_proposition_bindings", Name: "canonical_node_id", DataType: "text", NotNull: true},
	{Migration: propositionBindingMigration, Table: "canonical_proposition_bindings", Name: "decision_by", DataType: "text", NotNull: true},
	{Migration: propositionBindingMigration, Table: "canonical_proposition_bindings", Name: "decision_reason", DataType: "text", NotNull: true},
	{Migration: propositionBindingMigration, Table: "canonical_proposition_bindings", Name: "request_hash", DataType: "text", NotNull: true},
	{Migration: propositionBindingMigration, Table: "canonical_proposition_binding_events", Name: "request_id", DataType: "text", NotNull: true},
	{Migration: propositionBindingMigration, Table: "canonical_proposition_binding_events", Name: "canonical_node_id", DataType: "text", NotNull: true},
	{Migration: propositionBindingMigration, Table: "canonical_proposition_binding_events", Name: "previous_ref", DataType: "text", NotNull: true},
	{Migration: propositionBindingMigration, Table: "canonical_proposition_binding_events", Name: "from_id", DataType: "text", NotNull: false},
	{Migration: propositionBindingMigration, Table: "canonical_proposition_binding_events", Name: "target_id", DataType: "text", NotNull: false},
	{Migration: propositionBindingMigration, Table: "canonical_proposition_binding_events", Name: "operation", DataType: "text", NotNull: true},
	{Migration: propositionBindingMigration, Table: "canonical_proposition_binding_events", Name: "decision_by", DataType: "text", NotNull: true},
	{Migration: propositionBindingMigration, Table: "canonical_proposition_binding_events", Name: "decision_reason", DataType: "text", NotNull: true},
	{Migration: propositionBindingMigration, Table: "canonical_proposition_binding_events", Name: "evidence_ref", DataType: "text", NotNull: true},
	{Migration: propositionBindingMigration, Table: "canonical_proposition_binding_events", Name: "revision", DataType: "bigint", NotNull: true},
	{Migration: propositionBindingMigration, Table: "canonical_proposition_binding_events", Name: "recorded_at", DataType: "timestamp with time zone", NotNull: true, Default: "clock_timestamp()"},
}
var propositionBindingConstraints = []requiredFixedCoreConstraint{
	{Migration: propositionBindingMigration, Table: "canonical_propositions", Name: "canonical_propositions_namespace_id_local_id_scope_ref_revi_key", Type: "u", Deferrable: false, InitiallyDeferred: false, Definition: "UNIQUE (namespace_id, local_id, scope_ref, revision)"},
	{Migration: propositionBindingMigration, Table: "canonical_propositions", Name: "canonical_propositions_pkey", Type: "p", Deferrable: false, InitiallyDeferred: false, Definition: "PRIMARY KEY (proposition_id)"},
	{Migration: propositionBindingMigration, Table: "canonical_propositions", Name: "canonical_propositions_check", Type: "c", Deferrable: false, InitiallyDeferred: false, Definition: "CHECK ((proposition_id = ('prop:sha256:'::text || encode(sha256(convert_to((((((((((((('23:proposition-identity/v1'::text || (octet_length(namespace_id))::text) || ':'::text) || namespace_id) || (octet_length(local_id))::text) || ':'::text) || local_id) || (octet_length(scope_ref))::text) || ':'::text) || scope_ref) || (octet_length(revision))::text) || ':'::text) || revision), 'UTF8'::name)), 'hex'::text))))"},
	{Migration: propositionBindingMigration, Table: "canonical_propositions", Name: "canonical_propositions_definition_check", Type: "c", Deferrable: false, InitiallyDeferred: false, Definition: "CHECK (((octet_length(definition) >= 1) AND (octet_length(definition) <= 8192)))"},
	{Migration: propositionBindingMigration, Table: "canonical_propositions", Name: "canonical_propositions_local_id_check", Type: "c", Deferrable: false, InitiallyDeferred: false, Definition: "CHECK (((octet_length(local_id) >= 1) AND (octet_length(local_id) <= 512)))"},
	{Migration: propositionBindingMigration, Table: "canonical_propositions", Name: "canonical_propositions_namespace_id_check", Type: "c", Deferrable: false, InitiallyDeferred: false, Definition: "CHECK (((octet_length(namespace_id) >= 1) AND (octet_length(namespace_id) <= 512)))"},
	{Migration: propositionBindingMigration, Table: "canonical_propositions", Name: "canonical_propositions_revision_check", Type: "c", Deferrable: false, InitiallyDeferred: false, Definition: "CHECK (((octet_length(revision) >= 1) AND (octet_length(revision) <= 512)))"},
	{Migration: propositionBindingMigration, Table: "canonical_propositions", Name: "canonical_propositions_scope_ref_check", Type: "c", Deferrable: false, InitiallyDeferred: false, Definition: "CHECK (((octet_length(scope_ref) >= 1) AND (octet_length(scope_ref) <= 512)))"},
	{Migration: propositionBindingMigration, Table: "canonical_proposition_bindings", Name: "canonical_proposition_bindings_canonical_node_id_key", Type: "u", Deferrable: false, InitiallyDeferred: false, Definition: "UNIQUE (canonical_node_id)"},
	{Migration: propositionBindingMigration, Table: "canonical_proposition_bindings", Name: "canonical_proposition_bindings_pkey", Type: "p", Deferrable: false, InitiallyDeferred: false, Definition: "PRIMARY KEY (request_id)"},
	{Migration: propositionBindingMigration, Table: "canonical_proposition_bindings", Name: "canonical_proposition_bindings_canonical_node_id_fkey", Type: "f", Deferrable: false, InitiallyDeferred: false, Definition: "FOREIGN KEY (canonical_node_id) REFERENCES canonical_graph_nodes(canonical_node_id)"},
	{Migration: propositionBindingMigration, Table: "canonical_proposition_bindings", Name: "canonical_proposition_bindings_decision_by_check", Type: "c", Deferrable: false, InitiallyDeferred: false, Definition: "CHECK (((octet_length(decision_by) >= 1) AND (octet_length(decision_by) <= 512)))"},
	{Migration: propositionBindingMigration, Table: "canonical_proposition_bindings", Name: "canonical_proposition_bindings_decision_reason_check", Type: "c", Deferrable: false, InitiallyDeferred: false, Definition: "CHECK (((octet_length(decision_reason) >= 1) AND (octet_length(decision_reason) <= 2048)))"},
	{Migration: propositionBindingMigration, Table: "canonical_proposition_bindings", Name: "canonical_proposition_bindings_proposition_id_fkey", Type: "f", Deferrable: false, InitiallyDeferred: false, Definition: "FOREIGN KEY (proposition_id) REFERENCES canonical_propositions(proposition_id)"},
	{Migration: propositionBindingMigration, Table: "canonical_proposition_bindings", Name: "canonical_proposition_bindings_request_id_check", Type: "c", Deferrable: false, InitiallyDeferred: false, Definition: "CHECK (((octet_length(request_id) >= 1) AND (octet_length(request_id) <= 512)))"},
	{Migration: propositionBindingMigration, Table: "canonical_proposition_binding_events", Name: "canonical_proposition_binding_events_pkey", Type: "p", Deferrable: false, InitiallyDeferred: false, Definition: "PRIMARY KEY (request_id)"},
	{Migration: propositionBindingMigration, Table: "canonical_proposition_binding_events", Name: "proposition_binding_event_revision_uq", Type: "u", Deferrable: false, InitiallyDeferred: false, Definition: "UNIQUE (canonical_node_id, revision)"},
	{Migration: propositionBindingMigration, Table: "canonical_proposition_binding_events", Name: "canonical_proposition_binding_events_canonical_node_id_fkey", Type: "f", Deferrable: false, InitiallyDeferred: false, Definition: "FOREIGN KEY (canonical_node_id) REFERENCES canonical_proposition_bindings(canonical_node_id)"},
	{Migration: propositionBindingMigration, Table: "canonical_proposition_binding_events", Name: "canonical_proposition_binding_events_decision_by_check", Type: "c", Deferrable: false, InitiallyDeferred: false, Definition: "CHECK (((octet_length(decision_by) >= 1) AND (octet_length(decision_by) <= 512)))"},
	{Migration: propositionBindingMigration, Table: "canonical_proposition_binding_events", Name: "canonical_proposition_binding_events_decision_reason_check", Type: "c", Deferrable: false, InitiallyDeferred: false, Definition: "CHECK (((octet_length(decision_reason) >= 1) AND (octet_length(decision_reason) <= 2048)))"},
	{Migration: propositionBindingMigration, Table: "canonical_proposition_binding_events", Name: "canonical_proposition_binding_events_evidence_ref_check", Type: "c", Deferrable: false, InitiallyDeferred: false, Definition: "CHECK (((octet_length(evidence_ref) >= 1) AND (octet_length(evidence_ref) <= 2048)))"},
	{Migration: propositionBindingMigration, Table: "canonical_proposition_binding_events", Name: "canonical_proposition_binding_events_from_id_fkey", Type: "f", Deferrable: false, InitiallyDeferred: false, Definition: "FOREIGN KEY (from_id) REFERENCES canonical_propositions(proposition_id)"},
	{Migration: propositionBindingMigration, Table: "canonical_proposition_binding_events", Name: "canonical_proposition_binding_events_operation_check", Type: "c", Deferrable: false, InitiallyDeferred: false, Definition: "CHECK ((operation = ANY (ARRAY['correct'::text, 'withdraw'::text, 'restore'::text])))"},
	{Migration: propositionBindingMigration, Table: "canonical_proposition_binding_events", Name: "canonical_proposition_binding_events_previous_ref_check", Type: "c", Deferrable: false, InitiallyDeferred: false, Definition: "CHECK (((octet_length(previous_ref) >= 1) AND (octet_length(previous_ref) <= 1024)))"},
	{Migration: propositionBindingMigration, Table: "canonical_proposition_binding_events", Name: "canonical_proposition_binding_events_request_id_check", Type: "c", Deferrable: false, InitiallyDeferred: false, Definition: "CHECK (((octet_length(request_id) >= 1) AND (octet_length(request_id) <= 512)))"},
	{Migration: propositionBindingMigration, Table: "canonical_proposition_binding_events", Name: "canonical_proposition_binding_events_revision_check", Type: "c", Deferrable: false, InitiallyDeferred: false, Definition: "CHECK ((revision > 0))"},
	{Migration: propositionBindingMigration, Table: "canonical_proposition_binding_events", Name: "canonical_proposition_binding_events_target_id_fkey", Type: "f", Deferrable: false, InitiallyDeferred: false, Definition: "FOREIGN KEY (target_id) REFERENCES canonical_propositions(proposition_id)"},
}
