// Package labstatus extracts source-grounded status records from a Lab STATUS.md.
package labstatus

const (
	// SchemaVersion identifies the public JSON envelope written by detective.
	SchemaVersion = "lab-status-extraction/v0"
	// ExtractorName identifies this extractor implementation.
	ExtractorName = "lab-status-extractor"
	// ExtractorVersion identifies the self-contained statement prompt and projection.
	ExtractorVersion = "0.1.2"
	// RowBatchSchemaVersion identifies the row-chunk experiment report.
	RowBatchSchemaVersion = "lab-status-row-batch/v0"
)

// Source describes bytes observed directly by the controller. These fields are
// not generated by the model.
type Source struct {
	Path             string          `json:"path"`
	SHA256           string          `json:"sha256"`
	Bytes            int             `json:"bytes"`
	Lines            int             `json:"lines"`
	SelectedSections []SourceSection `json:"selected_sections"`
}

// SourceSection is a controller-selected Markdown section with original line
// coordinates. The section includes its heading line.
type SourceSection struct {
	Heading   string `json:"heading"`
	StartLine int    `json:"start_line"`
	EndLine   int    `json:"end_line"`
}

// ExtractorInfo describes the program and model that produced candidate records.
type ExtractorInfo struct {
	Name    string `json:"name"`
	Version string `json:"version"`
	Model   string `json:"model"`
}

// Envelope is the validated, source-coordinate-bearing CLI result.
type Envelope struct {
	SchemaVersion string        `json:"schema_version"`
	Source        Source        `json:"source"`
	Extractor     ExtractorInfo `json:"extractor"`
	Result        CandidateSet  `json:"result"`
}

// RowBatch reports one extraction attempt per Markdown table row. Failed rows
// remain visible for evaluation and never become successful candidate records.
type RowBatch struct {
	SchemaVersion string        `json:"schema_version"`
	Source        Source        `json:"source"`
	Extractor     ExtractorInfo `json:"extractor"`
	Section       SourceSection `json:"section"`
	Rows          []RowOutcome  `json:"rows"`
	Summary       RowSummary    `json:"summary"`
}

// SourceRow identifies one controller-selected Markdown table row.
type SourceRow struct {
	StartLine int    `json:"start_line"`
	EndLine   int    `json:"end_line"`
	Text      string `json:"text"`
}

// RowOutcome is the controller disposition for one row-level model attempt.
type RowOutcome struct {
	Row    SourceRow     `json:"row"`
	Status string        `json:"status"`
	Result *CandidateSet `json:"result,omitempty"`
	Error  string        `json:"error,omitempty"`
	// Cause preserves error identity for in-process callers only. It must not
	// add upstream diagnostics to the serialized experiment report.
	Cause error `json:"-"`
}

// RowSummary counts outcomes without deriving any project status.
type RowSummary struct {
	Attempted    int `json:"attempted"`
	Validated    int `json:"validated"`
	Failed       int `json:"failed"`
	NotAttempted int `json:"not_attempted"`
}

// CandidateSet is the only object generated by the model. Every record remains
// a document-supported candidate until a later, explicit admission step.
type CandidateSet struct {
	Outcome          string       `json:"outcome"`
	Records          []Record     `json:"records"`
	Abstentions      []Abstention `json:"abstentions"`
	Limitations      []string     `json:"limitations"`
	AbstentionReason string       `json:"abstention_reason"`
}

// Record is one atomic assertion reported by the source document.
type Record struct {
	RecordType       string   `json:"record_type"`
	Subject          string   `json:"subject"`
	Statement        string   `json:"statement"`
	EpistemicClass   string   `json:"epistemic_class"`
	Status           string   `json:"status"`
	Scope            string   `json:"scope"`
	SelectionState   string   `json:"selection_state"`
	Citation         Citation `json:"citation"`
	BlockedBy        []string `json:"blocked_by"`
	DoesNotEstablish []string `json:"does_not_establish"`
	Qualifiers       []string `json:"qualifiers"`
}

// Citation binds a record to exact, one-based source lines. ExactQuote is
// hydrated from those lines by the controller, never copied by the model.
type Citation struct {
	StartLine  int    `json:"start_line"`
	EndLine    int    `json:"end_line"`
	ExactQuote string `json:"exact_quote,omitempty"`
}

// Abstention records a bounded item the model declined to infer.
type Abstention struct {
	Subject string `json:"subject"`
	Reason  string `json:"reason"`
}
